<?php
/*
    Gallery 2 Image Chooser
    Version 3.0 - updated 16 SEP 2007
    Documentation: http://g2image.steffensenfamily.com/

    Author: Kirk Steffensen with inspiration, code snippets,
        and assistance as listed in CREDITS.HTML

    Released under the GPL version 2.
    A copy of the license is in the root folder of this plugin.

    See README.HTML for installation info.
    See CHANGELOG.HTML for a history of changes.
*/

//  Automatically generated by gallery.module (admin/settings/gallery/g2image).
//  DO NOT EDIT

$g2ic_embedded_mode = TRUE;
$g2ic_gallery2_path = '/Applications/MAMP/htdocs/gallery2/';
$g2ic_use_full_path = TRUE;
$g2ic_gallery2_uri = '/gallery2/';
$g2ic_embed_uri = '/pgd/index.php?q=gallery';
$g2ic_drupal_g2_filter = TRUE;
$g2ic_drupal_g2_filter_prefix = 'G2';
$g2ic_language = 'en';
$g2ic_images_per_page = 20;
$g2ic_display_filenames = FALSE;
$g2ic_default_alignment = 'none';
$g2ic_custom_class_1 = 'not_used';
$g2ic_custom_class_2 = 'not_used';
$g2ic_custom_class_3 = 'not_used';
$g2ic_custom_class_4 = 'not_used';
$g2ic_class_mode = 'img';
$g2ic_default_action = 'drupal_g2_filter';
$g2ic_sortby = 'title_asc';
$g2ic_custom_url = 'http://';

?>
